version: "3"


volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:15.3-alpine
    expose:
      - "5432"
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  redis:
    image: redis:7.0.12-alpine
    command: redis-server --requirepass redis-pass
    ports:
      - "6379:6379"
  magical-pathways:
    build:
      dockerfile: Dockerfile
    image: magical-pathways:latest
    entrypoint: ./docker-compose-entrypoint.sh
    command: [ 'rails', 'server', '-b', '0.0.0.0', '-p', '3000' ]
    ports:
      - 3000:3000
    volumes:
      - ./services/callback-router:/callback-router
    stdin_open: true
    tty: true
    depends_on:
      - postgres
